### ISSUE TITLE
Certain characters break decryption

### ISSUE THREAD

**Issue by zkwj** [syntaxseed/dokucrypt2#10]
I've noticed an issue with greater/less than signs. Seems to happen when there is a second greater than sign. For instance the following two lines break and do not show the last 3 characters:

```
<SECRET LOCK=default COLLAPSED=1> abc123>321<cba </SECRET>

<SECRET LOCK=default COLLAPSED=1> abc123<321<cba </SECRET>
```

This is the only characters I've noticed as problematic. Let me know if you need any additional information.

Thanks!

**Comment by syntaxseed** [comment]
Hmmm.

**Comment by Vudubond** [comment]
Hello,

I can confirm that the issue is present in 2022-02-02 as well.

**Comment by syntaxseed** [comment]
Work Around:

To enter these characters in your content to be encrypted, please use the HTML entity equivalents:

* < = Use: `&lt;`
* \> = Use: `&gt;`

(Updated Wiki instructions on the plugin page.)

**Comment by Vudubond** [comment]
> Work Around:
> 
> To enter these characters in your content to be encrypted, please use the HTML entity equivalents:
> 
> * < = Use: `&lt;`
> * > = Use: `&gt;`
> 
> (Updated Wiki instructions on the plugin page.)

Thank you. It is fine.
