### ISSUE TITLE
Customize default display text

### ISSUE THREAD

**Issue by nwly** [syntaxseed/dokucrypt2#13]
From https://forum.dokuwiki.org/d/19383-dokucrypt2-plugin-how-can-i-change-the-default-display-text:

Would be great if it was possible to customize the default display text:

> Decrypt Encrypted Text [Toggle Visible]

E.g., so that it can be changed to something less verbose:

> Decrypt [Toggle]

**Comment by syntaxseed** [comment]
Unfortunately there isn't any configuration for this plugin. But you can change that text by editing line 101 in syntax.php.

**Comment by nwly** [comment]
Thanks.  If I make the edit, will that impact future upgrades?

**Comment by syntaxseed** [comment]
You will need to remake the one line change each time there's an update.... but I don't make new releases unless there are bug fixes. 😁 So very rare.

**Comment by nwly** [comment]
I made edits to both line 101 in ``syntax.php`` and line 213 in ``script.js``, and then restarted the server (``sudo /opt/bitnami/ctlscript.sh restart``), but it still shows up as Decrypt Encrypted Text.  Really weird - am I not restarting it properly?  Or do I need to uninstall the plugin, change the files, and perform a manual install?

**Comment by syntaxseed** [comment]
I suspect this is related to Dokuwiki's caching.

You might try editing the file or follow these tips:

https://www.dokuwiki.org/devel:caching#purging_the_cache
