### ISSUE TITLE
Text starting with '<' is not correctly handeled

### ISSUE THREAD

**Issue by t-oster** [syntaxseed/dokucrypt2#19]
Hi, when you try to encode text with '<', it does not show the content when decrypting.

```
<SECRET LOCK=default COLLAPSED=1>T@<t is a P@ssword!</SECRET>
```
encrypts and decrypts correctly in the backend, but when decrypted in the frontend, it only shows T@

**Comment by syntaxseed** [comment]
Thank you @t-oster for providing this PR. It has been merged.
