### ISSUE TITLE
Plugin incompatible with Dokuwiki Hogfather=

### ISSUE THREAD

**Issue by safaribaer** [syntaxseed/dokucrypt2#6]
Hi,
since one of the latest Dokuwiki updates I have some problems accessing the encrypted data. 
It can decrypt the data that is already encrypred but I can not create new encrypte datasets.
Also modifying already encrypted data is not possibe because the 'DecryptSecret' button between 'Save' and 'Preview' does not appear.
Thx

**Comment by impactfactory** [comment]
Perhaps same here: adding the secret tags is not doing anything... no encryption happening, no dialogue popping up.

**Comment by syntaxseed** [comment]
I will look into this. Thanks for the bug report.

**Comment by syntaxseed** [comment]
Temporary fix in place. Please update or un-install / re-install. This fix is under review/testing.

**Comment by impactfactory** [comment]
Thanx a lot for the superfast reply. re-installing has no effect yet.

**Comment by syntaxseed** [comment]
@impactfactory the new version 2020-10-14 fixes the problem on my instance of Dokuwiki HogFather. Please confirm you have that version, then shift+refresh & try again.

If it doesn't work, I need more info - like any errors appearing in your browser's js console.

**Comment by impactfactory** [comment]
It doesnt work, perhaps Im doing something wrong with the syntax? is it right to do this syntax: `<SECRET> xxxxx</SECRET>` f.e. to protect the passwort inbetween? No popup for encryption is showing up. On ftp / direct txt-file everything still visible. Release 2020-07-29 "Hogfather" and docscript 2020-10-14.

![image](https://user-images.githubusercontent.com/72793580/96259238-9f40ed00-0fbd-11eb-9ef6-43451ddb5d9c.png)

**Comment by syntaxseed** [comment]
@impactfactory .... do you have access to edit the file in your DokuWiki installation?

If so, I'm curious to try something. If you can open the file lib/plugins/dokucrypt2/action.php and comment out (two forward slashes) the defer line for the init javascript. Like so:

```php
$event->data["script"][] = array (
            "type" => "text/javascript",
            "src" => DOKU_BASE."lib/plugins/dokucrypt2/init.js",
            //"defer" => "defer",
            "_data" => "",
        );
```
Save the file, then shift-refresh your dokuwiki page. See if that solves it. 

Otherwise this is tough as I can't reproduce on my end. Maybe it's conflicting with other plugins.

**Comment by syntaxseed** [comment]
That syntax is correct. I wonder about something... give me a minute.

**Comment by impactfactory** [comment]
a new error happens, thats all

yes i have quite some plugins running. do you need a list? that would narrow it down as you for sure have some plugins too.

**Comment by syntaxseed** [comment]
@impactfactory .... I have attempted a fix for you. It's in another branch. If you can download the zip for this plugin and replace the files you are using in /lib/plugins/dokucrypt2/ with this:

https://github.com/syntaxseed/dokucrypt2/archive/hogfather-fix-1.zip

Shift+refresh your dokuwiki webpage then try again to create a secret block.

PS - thank you for your time helping to debug this. :)

**Comment by syntaxseed** [comment]
@impactfactory yes the comment out the defer line didn't work, I had deleted that comment. Try the new version of the plugin in the zip file above. Thank you so much for your help.

**Comment by impactfactory** [comment]
im glad to help - while sitting in a train with a mask :)

now the whole installation is crashing, my browser just says he cannot open this website...

**Comment by impactfactory** [comment]
ok, i found out why it crashed. you should not have folders like xxxdocucrypt2-old in the plugins folder. still testing

**Comment by impactfactory** [comment]
SORRY, NO DIFFERENCE

**Comment by impactfactory** [comment]
PERHAPS A HINT: IT DOESNT PARSE THE TAGS IN THE NON-EDIT VIEW

**Comment by syntaxseed** [comment]
> PERHAPS A HINT: IT DOESNT PARSE THE TAGS IN THE NON-EDIT VIEW

Correct, Dokuwiki syntax within an encrypted block are not parsed. This is already a reported enhancement request.

**Comment by syntaxseed** [comment]
Well... this is beyond my time and ability to fix. Both versions of the plugin work for me. I'll have to leave the bug open and see if anyone else wants to chime in or attempt a fix. I am in the process of getting advice on the DokuWiki forum. Sorry @impactfactory.

**Comment by impactfactory** [comment]
OK. I CAN ADD LIST OF PLUGINS. NOT GOOD THAT PLUGINS CAN INTERFERE EACH OTHER.

COULD YOU ADD THE LINK TO THE FORUM HERE?

THANK YOU.

**Comment by syntaxseed** [comment]
It would be better if you can disable all your plugins besides this one and see if the problem still occurs. As a free plugin that very few people use, I unfortunately don't have time to install and test against a bunch of plugins. :)

**Comment by syntaxseed** [comment]
I've been looking for advice related to this plugin here:

https://forum.dokuwiki.org/d/18356-plugin-dev-run-js-on-page-load

**Comment by impactfactory** [comment]
I deactivated all plugins and found out that the Plugin "Fastwiki" is causing docucrypt2 not to work. "Fastwiki" seems to have many bugs.

Also as I see it now: I wonder if it is intentional that this descryption message blocks appear?

![dokucrypt](https://user-images.githubusercontent.com/72793580/96438105-ae66ab80-1206-11eb-8a33-b986e818ac5a.png)

I don't understand what benefit it provides.

I disabled the toggle button in the javascript and did also the translations there. Now its really useful - thanx!!

**Comment by syntaxseed** [comment]
@impactfactory thanks for the research! I have added fastwiki to the list of conflicting plugins.

I will look into the spacing issue.

Yes you can toggle the visibility of the encrypted block. This was a feature of the original plugin which I took over.

**Comment by impactfactory** [comment]
nice. for endusers i woudl use this terms (german added)

display / anzeigen
hide / verstecken

and the toggle I would deactivate. seems to have no benefit in my case…..

I changed all secret tags to collapse=1. I would do that as default as it makes a page very confusing if you see this text about the javascript 20 times on it.

**Comment by syntaxseed** [comment]
@impactfactory 

I agree with several of your suggestions. PR #9 addresses these with a new version of DokuCrypt2: version 2020-10-19.

 - Added spacing between the decrypt and toggle visible links.
- Added CSS classes to links and PRE blocks to allow user styling.
- Encrypted blocks are now collapsed by default.

**Comment by syntaxseed** [comment]
Additional suggestions please create a new issue.
